"""CLI: calibrate a smartphone camera from a folder of chessboard photographs.

Run from the repository root (or the ``Assignments/`` workspace root with ``Module_2/``
prefixes)::

    python scripts/run_calibration.py \\
        --images-dir data/calibration_images \\
        --pattern 9x6 \\
        --square-size-mm 24.7 \\
        --out data/calibration.json \\
        --report results/calibration_report.md

The ``--square-size-mm`` value must be the **physically measured** printed square edge
length (see ``docs/calibration_capture_protocol.md``), never the nominal print size.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Allow running straight from a fresh clone (before `pip install -e .`).
_SRC = REPO_ROOT / "src"
if _SRC.is_dir() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import numpy as np  # noqa: E402

from module2.calibration import (  # noqa: E402
    CalibrationResult,
    calibrate_from_images,
    parse_pattern_size,
    save_calibration,
)
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}


def _collect_images(images_dir: Path) -> list[Path]:
    if not images_dir.is_dir():
        raise SystemExit(f"images dir not found: {images_dir}")
    return sorted(p for p in images_dir.iterdir() if p.suffix.lower() in IMAGE_EXTS)


def _format_report(result: CalibrationResult, images_dir: Path, total_images: int) -> str:
    K = np.asarray(result.camera_matrix, dtype=float)
    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    dist = np.asarray(result.dist_coeffs, dtype=float).ravel()
    per_view = result.per_view_errors
    failed = (
        ", ".join(Path(p).name for p in result.failed_images)
        if result.failed_images
        else "none — chessboard detected in every image"
    )
    lines = [
        "# Camera calibration — results",
        "",
        f"*Generated by `scripts/run_calibration.py` on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')} from real photographs "
        f"in `{images_dir}`.*",
        "",
        "## Method",
        "",
        "- Model: OpenCV pinhole camera model via `cv2.calibrateCamera`.",
        "- Corner detection: `cv2.findChessboardCorners` "
        "(`CALIB_CB_ADAPTIVE_THRESH | CALIB_CB_NORMALIZE_IMAGE`) refined with "
        "`cv2.cornerSubPix`.",
        f"- Target: {result.pattern_size[0]}×{result.pattern_size[1]} inner-corner "
        f"chessboard; measured square edge **{result.square_size_mm:.2f} mm**.",
        f"- Images: **{len(result.used_images)}/{total_images}** used.",
        f"- Images with no detected chessboard: {failed}.",
        f"- Image resolution: {result.image_size[0]}×{result.image_size[1]} px.",
        "",
        "## Camera intrinsic matrix K (pixels)",
        "",
        "```",
        f"[ {fx:10.3f}  {K[0,1]:10.3f}  {cx:10.3f} ]",
        f"[ {K[1,0]:10.3f}  {fy:10.3f}  {cy:10.3f} ]",
        f"[ {K[2,0]:10.3f}  {K[2,1]:10.3f}  {K[2,2]:10.3f} ]",
        "```",
        "",
        f"- fx = {fx:.3f} px, fy = {fy:.3f} px",
        f"- principal point (cx, cy) = ({cx:.3f}, {cy:.3f}) px",
        "",
        "## Distortion coefficients",
        "",
        "Order: (k1, k2, p1, p2, k3, ...)",
        "",
        "```",
        "[ " + "  ".join(f"{c:.6f}" for c in dist) + " ]",
        "```",
        "",
        "## Reprojection error",
        "",
        f"- Overall RMS: **{result.rms_reprojection_error:.4f} px**",
    ]
    if per_view:
        lines.append(
            f"- Per view (px): min {min(per_view):.4f}, mean "
            f"{sum(per_view) / len(per_view):.4f}, max {max(per_view):.4f}"
        )
    lines += [
        "",
        "These are measured values from the user's own smartphone photographs. "
        "See `data/calibration.json` for the machine-readable form.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Calibrate a smartphone camera from chessboard photographs."
    )
    parser.add_argument(
        "--images-dir",
        type=Path,
        default=REPO_ROOT / "data" / "calibration_images",
        help="folder of chessboard photos (default: data/calibration_images)",
    )
    parser.add_argument(
        "--pattern", default="9x6", help="inner-corner count, e.g. 9x6 (default: 9x6)"
    )
    parser.add_argument(
        "--square-size-mm",
        type=float,
        required=True,
        help="measured printed square edge length, in millimetres",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "data" / "calibration.json",
        help="output JSON path (default: data/calibration.json)",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=REPO_ROOT / "results" / "calibration_report.md",
        help="output Markdown report path (default: results/calibration_report.md)",
    )
    args = parser.parse_args(argv)

    if args.square_size_mm <= 0:
        raise SystemExit("--square-size-mm must be positive")

    pattern_size = parse_pattern_size(args.pattern)
    images = _collect_images(args.images_dir)
    if not images:
        raise SystemExit(
            f"no images ({', '.join(sorted(IMAGE_EXTS))}) found in {args.images_dir}"
        )

    print(f"Calibrating from {len(images)} image(s) in {args.images_dir} ...")
    result = calibrate_from_images(images, pattern_size, args.square_size_mm)

    save_calibration(result, args.out)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(_format_report(result, args.images_dir, len(images)))

    print(f"  images used:            {len(result.used_images)}/{len(images)}")
    if result.failed_images:
        print(
            "  chessboard NOT found:   "
            + ", ".join(Path(p).name for p in result.failed_images)
        )
    print(f"  RMS reprojection error: {result.rms_reprojection_error:.4f} px")
    print(f"  wrote {args.out}")
    print(f"  wrote {args.report}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
